disease_models/Liver/app.py
from flask import Flask, render_template, url_for, flash, redirect
import joblib
from flask import request
import numpy as np

app = Flask(__name__, template_folder='templates')

@app.route("/")

@app.route("/liver")
def cancer():
    return render_template("liver.html")

def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1,size)
    if(size==7):
        loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Liver\liver_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]

@app.route('/predict', methods = ["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
         #liver
        if(len(to_predict_list)==7):
            result = ValuePredictor(to_predict_list,7)
    
    if(int(result)==1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return(render_template("cancerresult.html", prediction_text=prediction))

if __name__ == "__main__":
    app.run(debug=False,host='0.0.0.0')

disease_models/Liver/liver_blueprint.py
# from flask import Blueprint, render_template
# import joblib
# from flask import request
# import numpy as np
#
# liver_blueprint = Blueprint("liver", __name__, template_folder="templates")
#
# @liver_blueprint.route("/liver")
# def liver():
#     return render_template("liver.html")
#
#
# def ValuePredictor(to_predict_list, size):
#     to_predict = np.array(to_predict_list).reshape(1, size)
#     if (size == 7):
#         loaded_model = joblib.load(
#             r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Liver\liver_model.pkl')
#         result = loaded_model.predict(to_predict)
#     return result[0]
#
#
# @liver_blueprint.route('/predict', methods=["POST"])
# def predict():
#     if request.method == "POST":
#         to_predict_list = request.form.to_dict()
#         to_predict_list = list(to_predict_list.values())
#         to_predict_list = list(map(float, to_predict_list))
#         # liver
#         if (len(to_predict_list) == 7):
#             result = ValuePredictor(to_predict_list, 7)
#
#     if (int(result) == 1):
#         prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
#     else:
#         prediction = "No need to fear. You have no dangerous symptoms of the disease"
#     return (render_template("cancerresult.html", prediction_text=prediction))




from flask import Blueprint, render_template
import joblib
from flask import request
import numpy as np
import sqlite3

liver_blueprint = Blueprint("liver", __name__, template_folder="templates")

@liver_blueprint.route("/liver")
def liver():
    return render_template("liver.html")

def insert_liver_data(total_bilirubin, direct_bilirubin, alkaline_phosphotase,
                      alamine_aminotransferase, total_proteins, albumin,
                      albumin_and_globulin_ratio, result):
    conn = sqlite3.connect('medical_data.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO liver_predictions (
            total_bilirubin, direct_bilirubin, alkaline_phosphotase,
            alamine_aminotransferase, total_proteins, albumin,
            albumin_and_globulin_ratio, result
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (total_bilirubin, direct_bilirubin, alkaline_phosphotase,
          alamine_aminotransferase, total_proteins, albumin,
          albumin_and_globulin_ratio, result))
    conn.commit()
    conn.close()

def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if (size == 7):
        loaded_model = joblib.load(
            r'C:\Users\Lenovo\Downloads\Health-App-main-Updated\Health-App-main-Updated\disease_models\Liver\liver_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@liver_blueprint.route('/predict', methods=["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        # liver
        if (len(to_predict_list) == 7):
            result = ValuePredictor(to_predict_list, 7)
            insert_liver_data(
                to_predict_list[0],
                to_predict_list[1],
                to_predict_list[2],
                to_predict_list[3],
                to_predict_list[4],
                to_predict_list[5],
                to_predict_list[6],
                result
            )

    if (int(result) == 1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return (render_template("liverresult.html", prediction_text=prediction))

disease_models/Liver/templates/liver.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="../static/img/health.ico">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
    *{
    margin:0;
    padding:0;
    font-family: 'Josefin Sans', sans-serif;
    }
    html,
    body,
    header,
    #intro {
    height: 100%;
    }
    img {
    display: block;
    max-width: 100%;
    height: auto;
    }
    </style>
    <title>Liver Disease Prediction</title>
  </head>
  <body>
    <header>
<!--      <nav class="navbar navbar-expand-md navbar-dark bg-dark">-->
<!--        <a class="navbar-brand" href="index.html">Health App</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--          <ul class="navbar-nav mr-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="heart.html">Heart Disease<span class="sr-only">(current)</span></a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="kidney.html">Kidney Disease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="diabetes.html">Diabetes</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="liver.html">Liver Diease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="cancer.html">Cancer</a>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </nav>-->
      <!--Mask-->
      <div id="intro" class="container-fluid view ">
        <h1 class="text-center text-capitalize pt-5">Know your chances of getting a liver disease in one Click!</h1>
        <hr class="w-75 mx-auto pt-5">
        <div class="row mb-5">
          <div class="col-lg-6 col-md-6 col-12 my-auto">
            <img src="https://img.freepik.com/premium-vector/liver-icon-trendy-flat-style-symbol-your-web-site-design-logo-app-ui_599062-3797.jpg?size=626&ext=jpg" class="float-left">
            
          </div>
          <div class="col-lg-6 col-md-6 col-12">
            <form action="{{ url_for('liver.predict')}}" method="post">
              <div class="form-group">
                <!-- TODO : Year to accept only year date picker -->
                <label for="Total Bilirubin">Total Bilirubin</label>
                <input class="form-control" type="number" id="Total Bilirubin" name="Total Bilirubin" required="required" placeholder="Enter the Total Bilirubin">
              </div>
              <div class="form-group">
                <label for="Direct_Bilirubin">Direct Bilirubin</label>
                <input class="form-control" type="number" step="any" id="Direct_Bilirubin" name="Direct_Bilirubin" required="required" placeholder="Enter the Direct_Bilirubin">
              </div>
              <div class="form-group">
                <label for="Alkaline_Phosphotase">Alkaline Phosphotase</label>
                <input class="form-control" type="number" id="Alkaline_Phosphotase" name="Alkaline_Phosphotase" required="required" placeholder="Enter the Alkaline Phosphotase">
              </div>
              <div class="form-group">
                <label for="Alamine_Aminotransferase">Alamine Aminotransferase</label>
                <input class="form-control" type="number" id="Alamine_Aminotransferase" name="Alamine_Aminotransferase" required="required" placeholder="Enter the Alamine Aminotransferase">
              </div>
              <div class="form-group">
                <label for="Total_Protiens">Total Protiens</label>
                <input class="form-control" type="number" id="Total_Protiens" name="Total_Protiens" required="required" placeholder="Enter the Total Protiens">
              </div>
              <div class="form-group">
                <label for="Albumin">Albumin</label>
                <input class="form-control" type="number" id="Albumin" name="Albumin" required="required" placeholder="Enter the Albumin">
              </div>
              <div class="form-group">
                <label for="Albumin_and_Globulin_Ratio">Albumin and Globulin Ratio</label>
                <input class="form-control" type="number" id="Albumin_and_Globulin_Ratio" name="Albumin_and_Globulin_Ratio" required="required" placeholder="Enter the Albumin and Globulin Ratio">
              </div>           
              <button type="submit" class="btn btn-danger">Predict</button>
            </form>
          </div>
        </div>
      </div>
      <!--/.Mask-->
    </header>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

disease_models/Liver/templates/liverresult.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <title>Kidney Result</title>
</head>
<style>
  #main-footer {
    color: #FFFFFF;
    font-family: "Segoe UI";
    background: #2B2B2B;
    text-align: center;
    margin-top: 75px;
    padding: 16px;
    bottom: 8px;
  }

  .img_holder img {
    max-width: 100%;
    max-height: 100%;
  }

  .btn-file {
    position: relative;
    overflow: hidden;
  }

  .btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
  }

  @media (max-width: 600px) {

    h2,
    h3,
    p {
      text-align: center;
    }

    .mt-4 {
      margin-top: 20px;
    }

    img {
      width: 200px
    }
  }
</style>

<body>



  <div class="container">


    <h2>2. Liver Disease</h2>
    <h2 style="color:red;"> {{ prediction_text }}</h2>
    <div style="text-align: center; margin-top: 20px ; margin-bottom: 20px;" >
      <img style="max-width: 400px" src="https://img.freepik.com/premium-vector/liver-icon-trendy-flat-style-symbol-your-web-site-design-logo-app-ui_599062-3797.jpg?size=626&ext=jpg" />
    </div>
  <h3>Overview</h3>
<p>Liver disease is any disturbance of liver function that causes illness. The liver is responsible for many critical functions within the body and should it become diseased or injured, the loss of those functions can cause significant damage to the body. Liver disease is also referred to as hepatic disease.<br>

Liver disease is a broad term that covers all the potential problems that cause the liver to fail to perform its designated functions. Usually, more than 75% or three quarters of liver tissue needs to be affected before a decrease in function occurs.<br></p>

<h3>Symptoms</h3>
<p>Classic symptoms of liver disease include:</p>
 <ul>
  <li>nausea</li>
  <li>vomiting</li>
  <li>right upper quadrant abdominal pain, and </li>
  <li>jaundice (a yellow discoloration of the skin due to elevated bilirubin concentrations in the bloodstream).</li>
</ul>
<br>
<hr>
<br>


</div>

</body>

</html>

disease_models/Liver/templates/result.html
<!doctype html>
<html>
   <body>
       <h1> {{ prediction_text }}</h1>
   </body>
</html>