disease_models/Diabetes/app.py
from flask import Flask, render_template, url_for, flash, redirect
import joblib
from flask import request
import numpy as np

app = Flask(__name__, template_folder='templates')

@app.route("/")

@app.route("/Diabetes")
def cancer():
    return render_template("diabetes.html")

def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1,size)
    if(size==6):
        loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\Diabetes_API\diabetes_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]

@app.route('/predict', methods = ["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
         #diabetes
        if(len(to_predict_list)==6):
            result = ValuePredictor(to_predict_list,6)
    
    if(int(result)==1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return(render_template("cancerresult.html", prediction_text=prediction))

if __name__ == "__main__":
    app.run(debug=False,host='0.0.0.0')

disease_models/Diabetes/diabetes_blueprint.py
# # disease_models/Diabetes/diabetes_blueprint.py
# from flask import Blueprint, render_template
# import joblib
# from flask import request
# import numpy as np
#
# diabetes_blueprint = Blueprint("diabetes", __name__, template_folder="templates")
#
# @diabetes_blueprint.route("/diabetes")
# def diabetes():
#     return render_template("diabetes.html")
#
#
# def ValuePredictor(to_predict_list, size):
#     to_predict = np.array(to_predict_list).reshape(1, size)
#     if (size == 6):
#         loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Diabetes\diabetes_model.pkl')
#         result = loaded_model.predict(to_predict)
#     return result[0]
#
#
# @diabetes_blueprint.route('/predict', methods=["POST"])
# def predict():
#     if request.method == "POST":
#         to_predict_list = request.form.to_dict()
#         to_predict_list = list(to_predict_list.values())
#         to_predict_list = list(map(float, to_predict_list))
#         # diabetes
#         if (len(to_predict_list) == 6):
#             result = ValuePredictor(to_predict_list, 6)
#
#     if (int(result) == 1):
#         prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
#     else:
#         prediction = "No need to fear. You have no dangerous symptoms of the disease"
#     return (render_template("cancerresult.html", prediction_text=prediction))



# disease_models/Diabetes/diabetes_blueprint.py
from flask import Blueprint, render_template
import joblib
from flask import request
import numpy as np
import sqlite3

diabetes_blueprint = Blueprint("diabetes", __name__, template_folder="templates")

@diabetes_blueprint.route("/diabetes")
def diabetes():
    return render_template("diabetes.html")

def insert_diabetes_data(pregnancies, glucose, blood_pressure, bmi, diabetes_pedigree_function, age, result):
    conn = sqlite3.connect('medical_data.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO diabetes_predictions (pregnancies, glucose, blood_pressure, bmi, diabetes_pedigree_function, age, result)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (pregnancies, glucose, blood_pressure, bmi, diabetes_pedigree_function, age, result))
    conn.commit()
    conn.close()



def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if (size == 6):
        loaded_model = joblib.load(r'C:\Users\Lenovo\Downloads\Health-App-main-Updated\Health-App-main-Updated\disease_models\Diabetes\diabetes_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@diabetes_blueprint.route('/predict', methods=["POST"])
def predict():                                                                       
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        # diabetes
        if (len(to_predict_list) == 6):
            result = ValuePredictor(to_predict_list, 6)
            insert_diabetes_data(
                to_predict_list[0],
                to_predict_list[1],
                to_predict_list[2],
                to_predict_list[3],
                to_predict_list[4],
                to_predict_list[5],
                result
            )

    if (int(result) == 1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return (render_template("diabetesresult.html", prediction_text=prediction))

disease_models/Diabetes/templates/diabetes.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="../static/img/health.ico">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
    *{
    margin:0;
    padding:0;
    font-family: 'Josefin Sans', sans-serif;
    }
    html,
    body,
    header,
    #intro {
    height: 100%;
    }
    img {
    display: block;
    max-width: 100%;
    height: auto;
<!--    width:40vw;-->
<!--    height:80vh;-->
<!--    margin-left:3vw;-->
    }
    </style>
    <title>Diabetes Prediction</title>
  </head>
  <body>
    <header>
<!--      <nav class="navbar navbar-expand-md navbar-dark bg-dark">-->
<!--        <a class="navbar-brand" href="index.html">Health App</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--          <ul class="navbar-nav mr-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="heart.html">Heart Disease<span class="sr-only">(current)</span></a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="kidney.html">Kidney Disease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="diabetes.html">Diabetes</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="liver.html">Liver Diease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="cancer.html">Cancer</a>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </nav>-->
      <!--Mask-->
      <div id="intro" class="container-fluid view ">
        <h1 class="text-center text-capitalize pt-4">Know your chances of getting diabetes in one Click!</h1>
        <hr class="w-75 mx-auto pt-2">
        <div class="row mb-5">
          <div class="col-lg-6 col-md-6 col-12 my-auto">
            <img src="https://img.freepik.com/premium-photo/measuring-glucose-level-blood-isolated-white_392895-265897.jpg" class="float-left">

          </div>
          <div class="col-lg-6 col-md-6 col-12">
            <form action="{{ url_for('diabetes.predict')}}" method="post">
              <div class="form-group">
                <!-- TODO : Year to accept only year date picker -->
                <label for="Pregnancies">No. of Pregnencies</label>
                <input class="form-control" type="number" id="Pregnancies" name="Pregnancies" required="required" placeholder="No. of Pregnencies">
              </div>
              <div class="form-group">
                <label for="Glucose">Glucose Level</label>
                <input class="form-control" type="number" step="any" id="Glucose" name="Present_Price" required="required" placeholder="Glucose Level">
              </div>
              <div class="form-group">
                <label for="BloodPressure">Current Blood Pressure</label>
                <input class="form-control" type="number" id="BloodPressure" name="BloodPressure" required="required" placeholder="Current Blood Pressure">
              </div>
              <div class="form-group">
                <label for="BMI">Enter the Body Mass Index</label>
                <input class="form-control" type="number" id="BMI" name="BMI" required="required" placeholder="Body Mass Index">
              </div>
              <div class="form-group">
                <label for="DiabetesPedigreeFunction">Diabetes Pedigree Function</label>
                <input class="form-control" type="number" id="DiabetesPedigreeFunction" name="DiabetesPedigreeFunction" required="required" placeholder="Diabetes Pedigree Function">
              </div>
              <div class="form-group">
                <label for="Age">Age</label>
                <input class="form-control" type="number" id="Age" name="Age" required="required" placeholder="Age">
              </div>
              
              
              
              <button type="submit" class="btn btn-danger">Predict</button>
            </form>
          </div>
        </div>
      </div>
      <!--/.Mask-->
    </header>
    <br><br>
    <hr>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

disease_models/Diabetes/templates/diabetesresult.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <title>Diabetes Result</title>
</head>
<style>
  #main-footer {
    color: #FFFFFF;
    font-family: "Segoe UI";
    background: #2B2B2B;
    text-align: center;
    margin-top: 75px;
    padding: 16px;
    bottom: 8px;
  }

  .img_holder img {
    max-width: 100%;
    max-height: 100%;
  }

  .btn-file {
    position: relative;
    overflow: hidden;
  }

  .btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
  }

  @media (max-width: 600px) {

    h2,
    h3,
    p {
      text-align: center;
    }

    .mt-4 {
      margin-top: 20px;
    }

    img {
      width: 200px
    }
  }
</style>

<body>

  <header class="site-header">


  </header>

  <div class="container">


    <h2>2. Diabetes</h2>
    <h2 style="color:red;"> {{ prediction_text }}</h2>
    <div style="text-align: center; margin-top: 20px ; margin-bottom: 20px;" >
      <img style="max-width: 300px" src="https://img.freepik.com/premium-photo/measuring-glucose-level-blood-isolated-white_392895-265897.jpg" />
    </div>
    <p>Diabetes is a disease that occurs when your blood glucose, also called blood sugar, is too high. Blood glucose is
      your main source of energy and comes from the food you eat. Insulin, a hormone made by the pancreas, helps glucose
      from food get into your cells to be used for energy.</p>
    <h3>What health problems can people with diabetes develop? </h3>
    <p>Over time, high blood glucose leads to problems such as</p>

    <ul>
      <li>heart disease</li>
      <li>stroke</li>
      <li>kidney disease</li>
      <li>eye problems</li>
      <li>dental disease</li>
      <li>nerve damage</li>
      <li>foot problems</li>
    </ul>
    <br>
    <hr>
    <br>


</div>

</body>

</html>

disease_models/Diabetes/templates/result.html
<!doctype html>
<html>
   <body>
       <h1> {{ prediction_text }}</h1>
   </body>
</html>