disease_models/Breast_Cancer/app.py
from flask import Flask, render_template, url_for, flash, redirect
import joblib
from flask import request
import numpy as np

app = Flask(__name__, template_folder='templates')

@app.route("/")

@app.route("/cancer")
def cancer():
    return render_template(r"C:\Users\pradi\PycharmProjects\Health-App-main\Breast_Cancer API\cancer_model.pkl")

def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1,size)
    if(size==5):
        loaded_model = joblib.load('cancer_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]

@app.route('/predict', methods = ["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
         #cancer
        if(len(to_predict_list)==5):
            result = ValuePredictor(to_predict_list,5)
    
    if(int(result)==1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return(render_template("cancerresult.html", prediction_text=prediction))

if __name__ == "__main__":
    app.run(debug=False,host='0.0.0.0')

disease_models/Breast_Cancer/breast_cancer_blueprint.py
# # disease_models/Breast_Cancer/breast_cancer_blueprint.py
# from flask import Blueprint, render_template, request
# import joblib
# import numpy as np
# breast_cancer_blueprint = Blueprint("breast_cancer", __name__, template_folder="templates", static_url_path='/static')
#
# @breast_cancer_blueprint.route("/cancer")
# def cancer():
#     return render_template("cancer.html")
#
#
# def ValuePredictor(to_predict_list, size):
#     to_predict = np.array(to_predict_list).reshape(1, size)
#     if (size == 5):
#         loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Breast_Cancer\cancer_model.pkl')
#         result = loaded_model.predict(to_predict)
#     return result[0]
#
#
# @breast_cancer_blueprint.route('/predict', methods=["POST"])
# def predict():
#     if request.method == "POST":
#         to_predict_list = request.form.to_dict()
#         to_predict_list = list(to_predict_list.values())
#         to_predict_list = list(map(float, to_predict_list))
#         # cancer
#         if (len(to_predict_list) == 5):
#             result = ValuePredictor(to_predict_list, 5)
#
#     if (int(result) == 1):
#         prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
#     else:
#         prediction = "No need to fear. You have no dangerous symptoms of the disease"
#     return (render_template("cancerresult.html", prediction_text=prediction))



# # disease_models/Breast_Cancer/breast_cancer_blueprint.py
# from flask import Blueprint, render_template, request
# import joblib
# import numpy as np
# import mysql.connector
#
# breast_cancer_blueprint = Blueprint("breast_cancer", __name__, template_folder="templates", static_url_path='/static')
#
# db_config = {
#     'host': 'localhost',
#     'user': 'root',
#     'password': '',  # Replace with your database password
#     'database': 'skypia_healthcare',
# }
#
# def connect_to_database():
#     try:
#         return mysql.connector.connect(**db_config)
#     except mysql.connector.Error as err:
#         print("Error connecting to the database: {}".format(err))
#         return None
#
#
# def save_to_database(to_predict_list):
#     try:
#         conn = connect_to_database()
#         if conn:
#             cursor = conn.cursor()
#
#             insert_query = "INSERT INTO cancer (concave_points_mean, area_mean, radius_mean, perimeter_mean, concavity_mean) VALUES (%s, %s, %s, %s, %s)"
#
#             # Convert the values to strings as all columns are of type TEXT
#             data = tuple(map(str, to_predict_list))
#
#             cursor.execute(insert_query, data)
#
#             conn.commit()
#
#             cursor.close()
#             conn.close()
#
#             print("Data inserted successfully")
#     except mysql.connector.Error as err:
#         print("Error: {}".format(err))
#
#
# @breast_cancer_blueprint.route("/cancer")
# def cancer():
#     return render_template("cancer.html")
#
# def value_predictor(to_predict_list, size):
#     if size == 5:
#         loaded_model_path = r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Breast_Cancer\cancer_model.pkl'
#         loaded_model = joblib.load(loaded_model_path)
#         to_predict = np.array(to_predict_list).reshape(1, size)
#         result = loaded_model.predict(to_predict)
#         return result[0]
#
# @breast_cancer_blueprint.route('/predict', methods=["POST"])
# def predict():
#     result = None
#     if request.method == "POST":
#         to_predict_list = [float(request.form.get(key)) for key in ['concave_points_mean', 'area_mean', 'radius_mean', 'perimeter_mean', 'concavity_mean']]
#         result = value_predictor(to_predict_list, 5)
#
#         # Save data to the database
#         save_to_database(to_predict_list)
#
#     if result is not None:
#         prediction = "Sorry, you have a risk of the disease. Please consult a doctor immediately." if int(result) == 1 else "No need to fear. You have no dangerous symptoms of the disease."
#         return render_template("cancerresult.html", prediction_text=prediction)
#     else:
#         return "Error in prediction."


# disease_models/Breast_Cancer/breast_cancer_blueprint.py
from flask import Blueprint, render_template, request
import joblib
import numpy as np
import sqlite3

breast_cancer_blueprint = Blueprint("breast_cancer", __name__, template_folder="templates", static_url_path='/static')


@breast_cancer_blueprint.route("/cancer")
def cancer():
    return render_template("cancer.html")


def insert_data(concave_points_mean, area_mean, radius_mean, perimeter_mean, concavity_mean, result):
    conn = sqlite3.connect('medical_data.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO breast_cancer (concave_points_mean, area_mean, radius_mean, perimeter_mean, concavity_mean, result)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (concave_points_mean, area_mean, radius_mean, perimeter_mean, concavity_mean, result))
    conn.commit()
    conn.close()


def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if (size == 5):
        loaded_model = joblib.load(
            r'C:\Users\Lenovo\Downloads\Health-App-main-Updated\Health-App-main-Updated\disease_models\Breast_Cancer\cancer_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@breast_cancer_blueprint.route('/predict', methods=["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))

        # cancer
        if (len(to_predict_list) == 5):
            result = ValuePredictor(to_predict_list, 5)
            insert_data(
                to_predict_list[0],
                to_predict_list[1],
                to_predict_list[2],
                to_predict_list[3],
                to_predict_list[4],
                result
            )

    if (int(result) == 1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return (render_template("cancerresult.html", prediction_text=prediction))

disease_models/Breast_Cancer/templates/cancer.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="../static/img/health.ico">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
    *{
    margin:0;
    padding:0;
    font-family: 'Josefin Sans', sans-serif;
    }
    html,
    body,
    header,
    #intro {
    height: 100%;
    }
    img {
    display: block;
    max-width: 100%;
    height: auto;
    }

    </style>
    <title>Breast Cancer Prediction</title>
  </head>
  <body>
    <header class="pb-5">
<!--      <nav class="navbar navbar-expand-md navbar-dark bg-dark">-->
<!--        <a class="navbar-brand" href="index.html">Health App</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--          <ul class="navbar-nav mr-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="heart.html">Heart Disease<span class="sr-only">(current)</span></a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="kidney.html">Kidney Disease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="diabetes.html">Diabetes</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="liver.html">Liver Diease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="cancer.html">Cancer</a>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </nav>-->
      <!--Mask-->
      <div id="intro" class="container-fluid view">
        <h1 class="text-center text-capitalize pt-3">Know your chances of getting Breast Cancer in one Click!</h1>
        <hr class="w-75 mx-auto pt-1 ">
        <div class="row mb-5">
          <div class="col-lg-6 col-md-6 col-12 my-auto">
         <img src="https://st2.depositphotos.com/5398292/8972/v/950/depositphotos_89720090-stock-illustration-breast-cancer-awareness.jpg" class=" mt-5 float-left">
            <h3>{{ prediction_text }}</h3>
          </div>
          <div class="col-lg-6 col-md-6 col-12 ">
            <form action="{{ url_for('breast_cancer.predict')}}" method="POST">
              <div class="form-group">

                <br><br><br>
                <label for="concave points_mean">Mean of the Concave Points</label>
                <input class="form-control" type="number" id="concave points_mean" name="concave points_mean" required="required" placeholder="Mean of the Concave Points">
              </div>
              <div class="form-group">
                <label for="area_mean">Mean of the Area</label>
                <input class="form-control" type="number" step="any" id="area_mean" name="area_mean" required="required" placeholder="Mean of the Area">
              </div>
              <div class="form-group">
                <label for="radius_mean">Mean of the Radius</label>
                <input class="form-control" type="number" id="radius_mean" name="radius_mean" required="required" placeholder="Mean of the radius">
              </div>
              <div class="form-group">
                <label for="perimeter_mean">Mean of the Perimeters</label>
                <input class="form-control" type="number" id="perimeter_mean" name="perimeter_mean" required="required" placeholder="Mean of the Parameter">
              </div>
              <div class="form-group">
                <label for="concavity_mean">Mean of the Concavity</label>
                <input class="form-control" type="number" id="concavity_mean" name="concavity_mean" required="required" placeholder="Mean of the concavity">
              </div>
              <button type="submit" class="btn btn-danger">Predict</button>
            </form>
          </div>
        </div>
      </div>
        <br><br>
      <!--/.Mask-->
    </header>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </body>
</html>

disease_models/Breast_Cancer/templates/cancerresult.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	<title>Cancer Result</title>
</head>
<style>
	 #main-footer
    {
      color: #FFFFFF;
      font-family: "Segoe UI";
      background: #2B2B2B;
      text-align: center;
      margin-top: 75px;
      padding: 16px;
      bottom: 8px;
    }

    .img_holder img{
        max-width: 100%; max-height: 100%;
    }

    .btn-file {
    position: relative;
    overflow: hidden;
    }
    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }
      @media (max-width: 600px) {
            h2, h3, p{
                text-align: center;
            }

            .mt-4 {
                margin-top: 20px;
            }
            img{
               width: 200px
            }
        }
</style>
<body>

	<header class="site-header">


</header>

	<div class="container">

    <h2>1. Breast Cancer </h2>
         <h2 style="color:red;"> {{ prediction_text }}</h2>
    <div style="text-align: center; margin-top: 20px">
       <img style="max-width: 400px" src="https://st2.depositphotos.com/5398292/8972/v/950/depositphotos_89720090-stock-illustration-breast-cancer-awareness.jpg"/>
   </div>
    <p>Breast cancer is cancer that develops from breast tissue. Signs of breast cancer may include a lump in the breast, a change in breast shape, dimpling of the skin, fluid coming from the nipple, a newly inverted nipple, or a red or scaly patch of skin.<br></p>

    <h3>Symptoms</h3>
    <p>Signs and symptoms of breast cancer may include:</p>
    <ul>
      <li>A breast lump or thickening that feels different from the surrounding tissue</li>
      <li>Change in the size, shape or appearance of a breast
      </li>
      <li>
        Changes to the skin over the breast, such as dimpling
      </li>
      <li>
        A newly inverted nipple
      </li>
      <li>Peeling, scaling, crusting or flaking of the pigmented area of skin surrounding the nipple (areola) or breast skin</li>
      <li>Redness or pitting of the skin over your breast, like the skin of an orange</li>
    </ul>
    <h3>Causes</h3>
    <p>Doctors know that breast cancer occurs when some breast cells begin to grow abnormally. These cells divide more rapidly than healthy cells do and continue to accumulate, forming a lump or mass. Cells may spread (metastasize) through your breast to your lymph nodes or to other parts of your body.<br>
Breast cancer most often begins with cells in the milk-producing ducts (invasive ductal carcinoma). Breast cancer may also begin in the glandular tissue called lobules (invasive lobular carcinoma) or in other cells or tissue within the breast.
<br>
Researchers have identified hormonal, lifestyle and environmental factors that may increase your risk of breast cancer. But it's not clear why some people who have no risk factors develop cancer, yet other people with risk factors never do. It's likely that breast cancer is caused by a complex interaction of your genetic makeup and your environment.</p>
<br>
<hr>
<br>


</body>
</html>

disease_models/Breast_Cancer/templates/result.html
<!doctype html>
<html>
   <body>
       <h1> {{ prediction_text }}</h1>
   </body>
</html>