disease_models/Heart/app.py
from flask import Flask, render_template, url_for, flash, redirect
import joblib
from flask import request
import numpy as np

app = Flask(__name__, template_folder='templates')

@app.route("/")

@app.route("/Heart")
def cancer():
    return render_template("heart.html")

def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1,size)
    if(size==7):
        loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\Heart_API\heart_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]

@app.route('/predict', methods = ["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
         #diabetes
        if(len(to_predict_list)==7):
            result = ValuePredictor(to_predict_list,7)
    
    if(int(result)==1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return(render_template("cancerresult.html", prediction_text=prediction))

if __name__ == "__main__":
    app.run(debug=False,host='0.0.0.0')

disease_models/Heart/heart_blueprint.py
# from flask import Blueprint, render_template
# import joblib
# from flask import request
# import numpy as np
#
# heart_blueprint = Blueprint("heart", __name__, template_folder="templates")
#
# @heart_blueprint.route("/heart")
# def heart():
#     return render_template("heart.html")
#
#
# def ValuePredictor(to_predict_list, size):
#     to_predict = np.array(to_predict_list).reshape(1, size)
#     if (size == 7):
#         loaded_model = joblib.load(r'C:\Users\pradi\PycharmProjects\Health-App-main\disease_models\Heart\heart_model.pkl')
#         result = loaded_model.predict(to_predict)
#     return result[0]
#
#
# @heart_blueprint.route('/predict', methods=["POST"])
# def predict():
#     if request.method == "POST":
#         to_predict_list = request.form.to_dict()
#         to_predict_list = list(to_predict_list.values())
#         to_predict_list = list(map(float, to_predict_list))
#         # diabetes
#         if (len(to_predict_list) == 7):
#             result = ValuePredictor(to_predict_list, 7)
#
#     if (int(result) == 1):
#         prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
#     else:
#         prediction = "No need to fear. You have no dangerous symptoms of the disease"
#     return (render_template("cancerresult.html", prediction_text=prediction))



from flask import Blueprint, render_template
import joblib
from flask import request
import numpy as np
import sqlite3

heart_blueprint = Blueprint("heart", __name__, template_folder="templates")

@heart_blueprint.route("/heart")
def heart():
    return render_template("heart.html")

def insert_heart_data(chest_pain_type, resting_blood_pressure, serum_cholesterol,
                      fasting_blood_sugar, resting_ecg, max_heart_rate_achieved,
                      exercise_induced_angina, result):
    conn = sqlite3.connect('medical_data.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO heart_predictions (
            chest_pain_type, resting_blood_pressure, serum_cholesterol,
            fasting_blood_sugar, resting_ecg, max_heart_rate_achieved,
            exercise_induced_angina, result
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (chest_pain_type, resting_blood_pressure, serum_cholesterol,
          fasting_blood_sugar, resting_ecg, max_heart_rate_achieved,
          exercise_induced_angina, result))
    conn.commit()
    conn.close()


def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if (size == 7):
        loaded_model = joblib.load(r'C:\Users\Lenovo\Downloads\Health-App-main-Updated\Health-App-main-Updated\disease_models\Heart\heart_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@heart_blueprint.route('/predict', methods=["POST"])
def predict():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        # diabetes
        if (len(to_predict_list) == 7):
            result = ValuePredictor(to_predict_list, 7)
            insert_heart_data(
                to_predict_list[0],
                to_predict_list[1],
                to_predict_list[2],
                to_predict_list[3],
                to_predict_list[4],
                to_predict_list[5],
                to_predict_list[6],
                result
            )

    if (int(result) == 1):
        prediction = "Sorry you chances of getting the disease. Please consult the doctor immediately"
    else:
        prediction = "No need to fear. You have no dangerous symptoms of the disease"
    return (render_template("heartresult.html", prediction_text=prediction))

disease_models/Heart/templates/heart.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="../static/img/health.ico">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
    *{
    margin:0;
    padding:0;
    font-family: 'Josefin Sans', sans-serif;
    }
    html,
    body,
    header,
    #intro {
    height: 100%;
    }
    img {
    display: block;
    max-width: 100%;
    height: auto;
    }
    </style>
    <title>Heart disease Prediction</title>
  </head>
  <body>
    <header>
<!--      <nav class="navbar navbar-expand-md navbar-dark bg-dark">-->
<!--        <a class="navbar-brand" href="index.html">Health App</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--          <ul class="navbar-nav mr-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="heart.html">Heart Disease<span class="sr-only">(current)</span></a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="kidney.html">Kidney Disease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="diabetes.html">Diabetes</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="liver.html">Liver Diease</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="cancer.html">Cancer</a>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </nav>-->
      <!--Mask-->
      <div id="intro" class="container-fluid view ">
        <h1 class="text-center text-capitalize pt-5">Know your chances of getting a heart disease in one Click!</h1>
        <hr class="w-75 mx-auto pt-5">
        <div class="row mb-5">
          <div class="col-lg-6 col-md-6 col-12 my-auto">
            <img src="https://st4.depositphotos.com/25453930/29252/v/450/depositphotos_292524582-stock-illustration-heart-rate-cardiogram-uses-white.jpg" class="float-left">
            
          </div>
          <div class="col-lg-6 col-md-6 col-12">
            <form action="{{ url_for('heart.predict')}}" method="post">
              <div class="form-group">
                <label for="cp">Chest Pain Type</label>
                <select class="form-control" id="cp" name = "cp" required="required" placeholder="Chest Pain Type">
                  <option value="1">Typical Angina</option>
                  <option value="2">Atypical Angina</option>
                  <option value="3">Non-Anginal Pain</option>
                  <option value="4">Asymptomatic</option>
                </select>
              </div>

              <div class="form-group">
                <!-- TODO : Year to accept only year date picker -->
                <label for="trestbps">Resting Blood Pressure (in mm Hg)</label>
                <input class="form-control" type="number" id="trestbps" name="trestbps" required="required" placeholder="Resting Blood Pressure">
              </div>

              <div class="form-group">
                <label for="chol">Serum Cholestoral in mg/dl</label>
                <input class="form-control" type="number" step="any" id="chol" name="chol" required="required" placeholder="Serum Cholestoral">
              </div>

              <div class="form-group">
                <label for="fbs">Fasting Blood Sugar</label>
                <select class="form-control" id="fbs" name = "fbs" required="required" placeholder="Fasting Blood Sugar">
                  <option value="0">Fasting Blood Sugar < 120 mg/dl</option>
                  <option value="1">Fasting Blood Sugar > 120 mg/dl</option>
                </select>
              </div>

              <div class="form-group">
                <label for="restecg">Resting Electro-cardiographic Result</label>
                <select class="form-control" type="number" id="restecg" name="restecg" required="required" placeholder="Resting Electro-cardiographic Result">
                <option value="0">Normal</option>
                <option value="1">having ST-T wave abnormality</option>
                <option value="2">showing probable or definite left ventricular hypertrophy</option>
            	</select>
              </div>
              
              <div class="form-group">
                <label for="thalach">Maximum Heart Rate Achieved</label>
                <input class="form-control" id="thalach" name = "thalach" required="required" >
              </div>

              <div class="form-group">
                <label for="exang">Exercise Induced Angina</label>
                <select class="form-control" id="exang" name = "exang" required="required" >
                  <option value="1">Yes</option>
                  <option value="0">No</option>
                </select>
              </div>
              <button type="submit" class="btn btn-danger">Predict</button>
            </form>
          </div>
        </div>
      </div>
      <!--/.Mask-->
    </header>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

disease_models/Heart/templates/heartresult.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <title>Heart Disease Result</title>
</head>
<style>
  #main-footer {
    color: #FFFFFF;
    font-family: "Segoe UI";
    background: #2B2B2B;
    text-align: center;
    margin-top: 75px;
    padding: 16px;
    bottom: 8px;
  }

  .img_holder img {
    max-width: 100%;
    max-height: 100%;
  }

  .btn-file {
    position: relative;
    overflow: hidden;
  }

  .btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
  }

  @media (max-width: 600px) {

    h2,
    h3,
    p {
      text-align: center;
    }

    .mt-4 {
      margin-top: 20px;
    }

    img {
      width: 200px
    }
  }
</style>

<body>

  <header class="site-header">


  </header>

  <div class="container">


    <h2>2. Heart Disease</h2>
    <h2 style="color:red;"> {{ prediction_text }}</h2>
    <div style="text-align: center; margin-top: 20px ; margin-bottom: 20px;" >
      <img style="max-width: 400px" src="https://st4.depositphotos.com/25453930/29252/v/450/depositphotos_292524582-stock-illustration-heart-rate-cardiogram-uses-white.jpg" />
    </div>
    <h3>Overview</h3>
    <p>Heart disease describes a range of conditions that affect your heart. Diseases under the heart disease umbrella
      include blood vessel diseases, such as coronary artery disease; heart rhythm problems (arrhythmias); and heart
      defects you're born with (congenital heart defects), among others.<br>
      The term "heart disease" is often used interchangeably with the term "cardiovascular disease." Cardiovascular
      disease generally refers to conditions that involve narrowed or blocked blood vessels that can lead to a heart
      attack, chest pain (angina) or stroke. Other heart conditions, such as those that affect your heart's muscle,
      valves or rhythm, also are considered forms of heart disease.<br>
      Many forms of heart disease can be prevented or treated with healthy lifestyle choices.</p>

    <h3>Symptoms</h3>
    <ul>
      <li>Chest pain, chest tightness, chest pressure and chest discomfort (angina)</li>
      <li>Shortness of breath</li>
      <li>Pain, numbness, weakness or coldness in your legs or arms if the blood vessels in those parts of your body are
        narrowed</li>
      <li>Pain in the neck, jaw, throat, upper abdomen or back</li>
    </ul>
    <br>
    <hr>
    <br>



</div>

</body>

</html>

disease_models/Heart/templates/result.html
<!doctype html>
<html>
   <body>
       <h1> {{ prediction_text }}</h1>
   </body>
</html>